name: estore_client
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  equatable: ^2.0.7
  dio: ^5.8.0+1
  dartz: ^0.10.1
  http: ^1.3.0
  get_it: ^7.6.7
  flutter_secure_storage: ^9.0.0
  flutter_bloc: ^8.1.3
  go_router: ^14.8.0
  google_maps_flutter: ^2.11.0
  permission_handler: ^11.4.0
  geolocator: ^13.0.3
  carousel_slider: ^5.0.0
  redacted: ^1.0.13
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/Icons/categoriesIcons/
    - assets/products/smartPhones/
    - assets/map_style.json
    - assets/map-markers/
    - assets/sliderImages/
    - assets/products/ps5games/
    - assets/companiesIcons/
flutter_intl:
  enabled: true
